- hosts: localhost
  become: yes
  tasks:
    - name: Pull Docker Image
      command: docker pull shrey1112/spe-mini-project

    - name: Run Docker Container
      command: docker run -d -p 5000:5000 shrey1112/spe-mini-project